### ISSUE TITLE
请问如何使用源码，win10来编译，我是新手，用的cmake编译c++，发现报错，难道不支持win10的编译吗？

### ISSUE THREAD

**Issue by DidaDidaDidaD** [xinntao/Real-ESRGAN-ncnn-vulkan#12]
请问如何使用源码，win10来编译，我是新手，用的cmake编译c++，发现报错，难道不支持win10的编译吗？

**Comment by DidaDidaDidaD** [comment]
问题解决了，多少给一些提示啊，就弄两个空文件夹放那，哎

**Comment by fanyuecheng** [comment]
我也不太懂这个编译哎 不知道那些spv.hex.h文件哪来的 好心银能不能给我一份呀
