### ISSUE TITLE
Add CPU support

### ISSUE THREAD

**Issue by pinoverclock** [xinntao/Real-ESRGAN-ncnn-vulkan#34]
Plesase add CPU support or at least when no GPU devices are available

I know it will be quite slow, but not every device has a gpu or not powerfull/compatible ones

**Comment by nonetrix** [comment]
Vulkan itself doesn't support software rendering, so with Vulkan it's not doable. But NCNN seems to support CPU, but that is not Vulkan. So it's maybe possible, although it would make the name ironic

**Comment by pinoverclock** [comment]
I get your point, anyway it's good to know NCNN supports using a CPU. Closing

**Comment by nonetrix** [comment]
Eh no reason to close it can be added probably is what I'm saying
