### ISSUE TITLE
Please support scale other than 4 if possible, thanks

### ISSUE THREAD

**Issue by CharlieDreemur** [xinntao/Real-ESRGAN-ncnn-vulkan#38]
Since now the realesrgan-x4plus only support scale 4 output as its name showed, I try to download 2x model RealESRGAN_x2plus but fail to use it. Please support the feature such as --outscale that allows any scales if possible, thanks.

**Comment by AlphaHasher** [comment]
Just downscale the image; this is a plus in many cases since you can now choose exactly what res you want to keep
