### ISSUE TITLE
Image tiles strangely merge

### ISSUE THREAD

**Issue by zetyquickly** [xinntao/Real-ESRGAN-ncnn-vulkan#39]
Hello,

Using v0.2.0 build on Ubuntu with realesrgan-x4plus weights and see the following result

![download](https://user-images.githubusercontent.com/25350960/215688824-6295d953-0bcb-4ca9-8a11-3692444beca3.png)

Why the tiles are merging the wrong way?

**Comment by zetyquickly** [comment]
This happens with JPG upscaling to -f PNG. If its -f JPG then it went ok

**Comment by zetyquickly** [comment]
duplicate of https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan/issues/19

**Comment by AlphaHasher** [comment]
This happens because you are using a model only designed for 4x scaling. Scale the image down to the size you want

**Comment by zetyquickly** [comment]
That works too
